### ISSUE TITLE
Switching off the static loader fallback.

### ISSUE THREAD

**Issue by pfrendo** [ocombe/ng2-translate#159]
As I get my translation from a sever sometimes it takes a bit longer for me to set the translation. If then the `translateService.use` is called without any translations being set it will try and fallback to the static loader. As I fully understand why it fullbacks I would like to have the option to ignore the static loader completely 

![image](https://cloud.githubusercontent.com/assets/13260474/16539647/d0135d98-4049-11e6-9e5d-18a301472223.png)

I'm not sure if you think it's a good idea, but in my case I will not use loaders I will manually set translations through my app so an option to "switch off" the Loader

**Comment by yaroslavya** [comment]
Can you just write your own loader and just return the data you use to set the translation there?
And then just bootstrap it instead of the static loader. Or if in your case theres a need to just get rid of the static loader just perform the bootstrap with some stub implementation of the TranslateLoader.

Not an expert in ng2-translate, just using it and it seems one of these ways should work :-)

**Comment by ocombe** [comment]
Yes, you can define your own TranslateLoader for that :-)

**Comment by pfrendo** [comment]
Question, what if I don't want a TranslateLoader :) ?

**Comment by ocombe** [comment]
Just provide an empty class as a TranslateLoader for now :-)

**Comment by pfrendo** [comment]
Ok, but that is why I left this issue to see if it makes sense to switch it off, maybe I didn't explain it correctly :) Sorry!

**Comment by ocombe** [comment]
Yes I understand what you ask, but it is not possible for the moment.
I will refactor the loaders when I can find some time, I'll take your request into account then.

**Comment by pfrendo** [comment]
Ok dude no worries! Thanks
