### ISSUE TITLE
(discussion) ng2-translate will become the officially recommended for localization

### ISSUE THREAD

**Issue by NoNameProvided** [ocombe/ng2-translate#203]
I am just letting you know, Ionic 2 team will recommend ng2-translate for localization in the future. https://github.com/driftyco/ionic/issues/7691#issuecomment-240467024

**Comment by ocombe** [comment]
Hello, thanks for letting me know about this!

>

**Comment by albanx** [comment]
This is an impure pipe, what I notice that is called on every single component change on the app. Is there any performance benchmark ?

**Comment by ocombe** [comment]
No, but if you can make one that'd be cool !

**Comment by ocombe** [comment]
I just added an example folder with an ionic 2 example, hope this helps !

**Comment by ocombe** [comment]
@albanx like I answered on stackoverflow:
It's not because the pipe is "impure" that is has bad performance. The official async pipe is impure as well, and the TranslatePipe is based on it (the original code is almost the same). It has to be impure in order to resolve promises and observables when the lang changes or when it gets remote translations. When that is not necessary it returns immediately and the impact is minimal.

**Comment by albanx** [comment]
@ocombe that is not true. I made some benchmark in a simple app with 4 components, each containing 3 to 4 translation pipes. just clicking on an input fields causes all the pipe to be called at least 10 times each, so there were was 4x4x10=160 calls times just on a single click.

I solved the i18n problem of my app by changing the pipe to pure, and added  just one parameter to the pipe (in this case was the language). The parameter change trigger the pipe to refresh just once.

Example: 
From <button md-button class="btn-register">{{'Register' | trpipe}}</button>

to <button md-button class="btn-register">{{'Register' | trpipe:tr.lang}}</button>

tr.lang will change when the language is changed.

**Comment by ocombe** [comment]
Yes they are called but it only does two === tests for each, which is very fast. That's why I said minimal.
You can test with an async pipe and it does about the same thing.

Yes, with the lang as a parameter it updates the pipe when the lang changes, but it complicated the templates a lot because you will have to add it everywhere.

**Comment by albanx** [comment]
I have added the parameter to the translation service as public variable, so yes I have to inject the translationService in all components... But I am a bit stingy :) so I prefer this way for the moment.

**Comment by ocombe** [comment]
You should use the OnPush change detection strategy then

**Comment by albanx** [comment]
Here is a code I post
http://stackoverflow.com/questions/39026907/angular2-event-emmiter-subscribe-vs-public-variable?noredirect=1#comment65421431_39026907
