### ISSUE TITLE
Why not `ng2-translate/index`?

### ISSUE THREAD

**Issue by SamVerschueren** [ocombe/ng2-translate#253]
Hi @ocombe. I was just wondering, why do we have to import from `ng2-translate/ng2-translate`? Why can't we change the main entrypoint to `index.ts`? I believe webpack automatically handles barrels so you can `import { TranslateService } from 'ng2-translate';` and SystemJS is easily configurable. Maybe it will support barrels in the future as well.

Maybe it's done on purpose and it has a valid reason, but it feels weird for me to type `ng2-translate` twice :).

**Comment by ocombe** [comment]
When I originally created the lib, angular was imported from `angular/angular` and I mimicked that.
I should change it so that you can import from index.ts, but it would be a breaking change... I should have done it as the same time as the 3.0.0 release...
Maybe I can support both for some time by cloning the current ng2-translate.ts into index.ts, I'll put it on my todo list

**Comment by SamVerschueren** [comment]
You don't have to clone it, just add this line to `index.ts`

```
export * from './ng2-translate';
```

And done :). 100% backwards compatible.

**Comment by ocombe** [comment]
that too :P

**Comment by SamVerschueren** [comment]
If you want I can do a PR when I find some time?

**Comment by ocombe** [comment]
That'd be great !
