### ISSUE TITLE
v3.1.2 - Incompatibility with application based on commonJs modules

### ISSUE THREAD

**Issue by paulcayon** [ocombe/ng2-translate#279]
**I'm submitting a ...** 
```
[x] bug report 
[ ] support request 
[ ] feature request
```

**Current behavior**

usage of es2015 module on compilations option make your library unusable to someone that use commonjs module on his project. It is the only one librairy I use that have this compilation option.

so, when I execute my project with your  last version, I have : an error like this 

```
Uncaught SyntaxError: Unexpected token import(anonymous function) 
@ app.js:137__webpack_require__ 
@ polyfills.js:51(anonymous function) 
@ core.module.ts?f874:14(anonymous function) 
@ app.js:121__webpack_require__ 
@ polyfills.js:51(anonymous function) 
@ app.module.ts?256a:5(anonymous function) 
@ app.js:115__webpack_require__ 
@ polyfills.js:51(anonymous function) 
@ main.browser.ts?147c:3(anonymous function) 
@ main.browser.ts?147c:22(anonymous function) 
@ app.js:87__webpack_require__ 
@ polyfills.js:51(anonymous function) 
@ app.js:6__webpack_require__ @ polyfills.js:51webpackJsonpCallback 
@ polyfills.js:22(anonymous function) 
@ app.js:1
log.js:6 Chrome DNS: Sending message to background... 
```

It is not to early to integrate this compilation option ?

**Comment by tim545** [comment]
Hey @paulcayon I had the same issue as you, I looked back through the history of the code and saw that the module loader had been switched from "commonjs" to "ES2015":

https://github.com/ocombe/ng2-translate/commit/ebcf7e83ecb1045cd996fd18029ecf8e002d13ba#diff-e5e546dd2eb0351f813d63d1b39dbc48L4

I assumed this was done intentionally so there wouldn't be an intention to switch it back (I suppose potentially other projects would break if they did).

From what I've seen the latest beta version of webpack 2 apparently solves this issue, personally I'm still using webpack 1.x because I want to wait for 2 to come out of beta first. So instead for the meantime I just forked the project and changed the tsconfig to use commonjs modules instead until I can update to webpack 2. You can set your package.json to load your forked package from the github tarball, like so:

`"ng2-translate": "https://github.com/tim545/ng2-translate/archive/v3.1.1.tar.gz"`

There's just one little caveat, in the ng2-translate package.json you need to add a version property or npm will complain, and then create a release for it in github so you can get a url like the one above.

It's not a great solution but it works for now, however I would like to know if it could be switched back...?

**Comment by paulcayon** [comment]
@tim545 Thanks for answer. I will try to use webpack 2.
I can't make a dependency with a github link, because I work for a bank, and it don't allow this ... I have to use a Nexus to download dependencies. Thanks to shared your version. I'm sure that it will be useful for some other persons.

**Comment by n00dl3** [comment]
I sucessfully used webpack 1.13.2 to load the module using babel-loader with this module config :
```javascript
    {
      test: /ng2-translate\/.*\.js$/,
      loader: "babel-loader?presets[]=es2015"
    }
```
@ocombe maybe you could document this in the `README.md` ?

**Comment by ocombe** [comment]
That's a good idea.
With webpack 2 it's easy, just add `"lib": ["es5", "dom"]` to your tsconfig.json file (in `compilerOptions`)

**Comment by n00dl3** [comment]
Just one question, I've seen you're french , like me (qui ne saute pas, n'est pas Lyonnais ! ^ ^). Will I meet you at ng-europe next week ?

**Comment by ocombe** [comment]
Sorry, I wish I could go but I have other (family) obligations :)
