### ISSUE TITLE
Detailed documentation for methods

### ISSUE THREAD

**Issue by MartinMuzatko** [ocombe/ng2-translate#28]
It is unclear if you have to use `useStaticFilesLoader` in conjunction with `getTranslation`.
Which is required and where (!) see #27.

It is unclear which path is used for the `useStaticFilesLoader`. Relative to directory of execution? Relative to file? Absolute?

Any additions to the documentation and a less vague description of the methods would be very much appreciated.

Thanks in advance.

**Comment by ocombe** [comment]
Yes, the fact is that I need to simplify the configuration of the lib, for the moment you have to call multiple functions and that is not clear/easy.
I should make it configurable all in one place with parameters that are simple to understand.

**Comment by DanielSchuech** [comment]
@ocombe I can just remember 3 commands(useStaticFilesLoader, setDefaultLanguage & use) to configure and i would say that they are essential to stay aplicable for different applications. Correct me if i miss somthing ;)

###### It is unclear if you have to use useStaticFilesLoader in conjunction with getTranslation.
getTranslation will deliver the translations of the given language with the current loader. There is currently just one loader available. That should be maybe written to the readme. So you have to use useStaticFilesLoader before you can access getTranslations. Otherwise you will get an error.

###### It is unclear which path is used for the useStaticFilesLoader. Relative to directory of execution? Relative to file? Absolute?

Its an absoulte path. Here an example (from docu): 
```js
var prefix = 'assets/i18n/';
var suffix = '.json';
translate.useStaticFilesLoader(prefix, suffix);
```
your used lang: en
GET /assets/i18n/en.json

**Comment by ocombe** [comment]
`useStaticFilesLoader` is now called by default in the constructor (unless you provide any other `TranslateLoader` instead), but it will use the default prefix/suffix (which are i18n & .json)
