### ISSUE TITLE
Problem with global visible translate pipe.

### ISSUE THREAD

**Issue by maxkarpovets** [ocombe/ng2-translate#302]
I want make translate pipe global visible in all application. I added TranslatePipe to declarations of main module, but I have error:

> Type TranslatePipe is part of the declarations of 2 modules: TranslateModule and AppModule! Please consider moving TranslatePipe to a higher module that imports TranslateModule and AppModule. You can also create a new NgModule that exports and includes TranslatePipe then import that NgModule in TranslateModule and AppModule.

How I can fix it?

**Comment by SamVerschueren** [comment]
Are you adding `TranslatePipe` to the `declarations` of your main module?

In order to get this working, make sure you use `TranslateModule.forRoot()` in your main module, probably `AppModule`. Also import `TranslateModule` in your `ShareModule`.

```ts
@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        TranslateModule.forRoot()
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

```ts
@NgModule({
    exports: [
        CommonModule,
        TranslateModule
    ]
})
export class SharedModule { }
```

The pattern here is that you import the `ShareModule` in every feature module. Because `TranslateModule` is exported in the `ShareModule`, the `TranslatePipe` will be available in that module as well. This is how modules work.

**Comment by maxkarpovets** [comment]
Can I import in once to AppModule and use it in all child modules?

**Comment by SamVerschueren** [comment]
No, that's not how modules work.

**Comment by maxkarpovets** [comment]
Thanks!

**Comment by lesliesu** [comment]
@SamVerschueren I am doing that way you mentioned above, It works for all components that in other modules, except components in my SharedModule it self.

`@NgModule({
  imports: [SharedModule, TranslateModule.forRoot(), ...],
  declarations: [AppComponent, LandingComponent],
  bootstrap: [AppComponent]
})
export class AppModule {}
`

@NgModule({
  imports: [TranslateModule...]
  exports: [TranslateModule]
})
export class SharedModule{}
`


At AppModule, I have tried to import `SharedModule.forRoot`  and `SharedModule`, both ways haven't worked for me?

Any ideas or suggestions would be appreciate.
