### ISSUE TITLE
How to read current language from ng-1 in a hybrid Angular app?

### ISSUE THREAD

**Issue by IonPopescu** [ocombe/ng2-translate#305]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

I'm using ng-2 translate in a hybrid ng-1/ng-2 app. My plan is to use Pascal Precht's angular-translate to handle localization in the ng-1 code, and ng-2 translate to handle localization in the ng-2 code of the app. 

In my existing ng-1 implementation, users can change their language from a dropdown, and it gets stored in $rootScope.currentLanguage. E.G. " $rootScope.currentLanguage = 'de' ". My question is:  how can I read this value from $rootScope when initializing ng-2 translate, and how watch it and change the current language on the fly in ng2-translate when it changes?

**Comment by SamVerschueren** [comment]
I have no idea how this works, but would it be possible to inject the rootscope to the main ng2 component.

```ts
class AppComponent {
    constructor(
        @Inject('$rootScope') private rootScope,
        private translate: TranslateService
    ) { }

    ngOnInit() {
        this.rootScope.$watch('currentLanguage', language => {
            this.translate.use(language);
        });
    }
}
```

Although not sure if you can inject `$rootScope` as per this issue https://github.com/angular/angular/issues/10590.

I'm also not sure if it's a good thing to add stuff to your `$rootScope`. Instead, it might be better to create a `languageService` that you use to change the language. Then you can inject that service and listen to changes or better, emit an event when the language has changed.

Just throwing some ideas out here because as I said before, I have no experience with hybrid angular apps.

**Comment by ocombe** [comment]
we should ask @amcdnl, he's the only one I know using an hydrib app in production

**Comment by amcdnl** [comment]
@SamVerschueren - chk this out https://github.com/swimlane/ng1-ng2-webpack-lazy-uirouter

**Comment by IonPopescu** [comment]
I made it work like this:

```
export class AppModule {

	constructor(
		private translateService: TranslateService,
		@Inject('$rootScope') private _rootScope: any
	){ 
        this.translateService.addLangs(["en", ...]);
        this.translateService.setDefaultLang('en');
		this._rootScope.$watch('currentLanguage', language => {
			this.translateService.use("api/localization/" + language); 
		});
	}

	ngDoBootstrap() {}
}
```

**Comment by lionelB** [comment]
@IonPopescu Hello, I 'm currently working on a hybrid app. my angularJs (using angular-gettext) and angular(ngx-translate). I'm having  translation problem when I want to downgrade an angular component used in an angularJs component.
Do you managed to make it work ?
thanks
