### ISSUE TITLE
TranslateService - get

### ISSUE THREAD

**Issue by MarcoMonterminiBolla** [ocombe/ng2-translate#314]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
In my component  i have to translate a string using "get" of Translate service like this this.translate.get("TESTLABEL").subscribe(v => this.translatedByCode = v);  
On application startup i set currently used language by a web api call.
In this way translate.get is not working   

**Expected/desired behavior**
I think that "get" should return the translation as soon as the translation object becomes available. is that right?

Thanks

**Reproduction of the problem**
Here my test project  https://plnkr.co/edit/BrINbUrhe3jSLwSMDhS2?p=preview

**Please tell us about your environment:**

* **ng2-translate version:** 3.2.1

* **Angular version:** 2.0.0
 
* **Browser:**  Chrome XX 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by SamVerschueren** [comment]
Could you elaborate? Not sure if I understand your issue.

Do you mean the observable should emit a new value when the language is changed?

**Comment by luigidallavalle** [comment]
I'm having the same issue as well:
if the language setting
`this.translate.use('en');`
comes after a call of
`this.translate.get("captionCode").subscribe(translated => this.myLocalizedString = translated);`

the `subscribe` does not return any translation, it returns che untranslated caption.

I expect the code inside `subscribe` it's executed once the translations are ready, but it seems not to do so.
I had a look at the plunker of @MarcoMonterminiBolla and what is happening is clear to me:

1. in AppComponent it simulates a delayed `this.translate.use('en');`
2. in the testComponent it translate a caption

due to the delay, the translation attempt occours before the `this.translate.use('en');`, and what happen is that the translation doesn't take place.
I think it's quite a common scenario, in my app the language is taken from a webapi response which could take some time.

**Comment by ocombe** [comment]
it makes sense, but `this.translate.use('en');` should always be called before any get, the best place is in your module that imports the TranslateModule (modules have constructors in which you can define some logic that is executed before the components).
If you don't know which lang to use and you end up calling get without any lang defined, then the scenario is logical. You might want to use the `MissingTranslationHandler` in this case (where you could for example subscribe to the `OnLangChange` event): https://github.com/ocombe/ng2-translate#how-to-handle-missing-translations

**Comment by ocombe** [comment]
Closing this issue, continuing in https://github.com/ocombe/ng2-translate/issues/330
