### ISSUE TITLE
ionic 2 - typescript visual studio project does not work with ng2-translate

### ISSUE THREAD

**Issue by walaa118** [ocombe/ng2-translate#327]
**Current behavior**
the application does not work once this import line 
import {TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';

founded in the app.ts 

no error , no exceptions and no page appear. 

find the following link for the project code : 
https://drive.google.com/open?id=0Bwwmz7gNBuPKbEZDb1MxaFJMYUE

you can finding in the app.ts file when i just wright the import 
[
import { TranslateService } from 'ng2-translate';
]
application itself does not work

**Comment by ocombe** [comment]
Hello,

change ` import {TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate/ng2-translate';` to ` import {TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate';` and it should work (notice that I import from `ng2-translate` instead of `ng2-translate/ng2-translate`)

**Comment by walaa118** [comment]
hello,
i already use the import as: 
import {TranslateService, TranslatePipe, TranslateLoader, TranslateStaticLoader} from 'ng2-translate';

but app.bundle.js does not start:  and no errors no views appear .

in package.json file :  "ng2-translate": "^4.0.0"

any help

**Comment by sajTempler** [comment]
same here, no errors but the app is dead
"ng2-translate": "^4.0.1"

**Comment by matejamateusz** [comment]
@sajTempler Confirmed, your solution works! ;)
