### ISSUE TITLE
Unexpected value 'TranslateModule' imported by the module 'userModule'

### ISSUE THREAD

**Issue by korosakikun** [ocombe/ng2-translate#370]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[X] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```
**Current behavior**
```
Unexpected value 'TranslateModule' imported by the module 'userModule'
```
I'm getting this error when i'm executing my application after i compiling with source code or git clone.
But if i take npm version, my application run without problem.

* **ng2-translate version:** >=3.1.3

* **Angular version:** 2.2.0
 
* **Browser:** [Chrome 50 ] 
 
* **Language:** [ES6/7]

**Comment by ocombe** [comment]
Why do you want to git clone the project instead of using npm to install it ?

**Comment by SamVerschueren** [comment]
Probably because it's mapped incorrectly in your SystemJS config. If you really want to build from source (not sure why though), have a look at [`npm link`](https://docs.npmjs.com/cli/link). It allows you to symlink a local directory as if it was installed via `npm`.

**Comment by korosakikun** [comment]
I want to add a function to TranslateModule like TranslatModule.forChild for load different translate for each module.

**Comment by SamVerschueren** [comment]
That's when you should use `npm link` instead of trying to `git clone` inside your repository.

1. Clone repository
2. Run `npm run build` inside the repository
3. Run `npm link` inside the repository
4. Run `npm link ng2-translate` inside your local repository instead of `npm install ng2-translate`

Also, I suggest opening a new issue regarding that feature so we can discuss this first (unless you don't want to do a PR). I don't want you to do all the work and then ending up with a feature that's already in there. Explain your use case clearly so we know exactly what you want.

**Comment by korosakikun** [comment]
Sorry i don't say but i'm use webpack for my application.

**Comment by SamVerschueren** [comment]
Not sure how webpack works, but it probably has a config file as well? Try using the `npm link` workflow, it's no different from `npm install`. It only picks your local version instead of the remote one.

**Comment by korosakikun** [comment]
okay i will test that

**Comment by korosakikun** [comment]
```npm link``` create a global symlink and i don't want use in global, so if you have a another method for compile without create a global symlink

**Comment by ocombe** [comment]
I think that you can use `npm link` with relative paths as well: `npm link ../../some-folder`

**Comment by korosakikun** [comment]
The problem is ```npm link``` create a global symbolic link, next it's create a another link from node_module to the first global link create. So i don't know how to do without create a global link.

**Comment by SamVerschueren** [comment]
That's how `npm link` works, by creating a global link first. I don't see any problem in doing that?

`/src/of/ng2-translate` <- `global/link/to/ng2-translate` <- `local/link/to/ng2-translate`

This means that if you change something in `/src/of/ng2-translate`, the changes will boil down to your `local/link/to/ng2-translate` in your Angular 2 project. What's wrong with this approach?

**Comment by korosakikun** [comment]
In my webpack config i create a alias for ng2-translate that links to `ng2-translate/bundles/index.js`
So normaly it's the link i need for my application.
But i have this error : `Unexpected value 'TranslateModule' imported by the module 'userModule'`

**Comment by SamVerschueren** [comment]
Ok, so either I don't get it or you don't get it :). So let me try to recap everything.

First revert everything and make it work with `npm install ng2-translate`. Remove the `git clone` stuff.

Run your application, works? Alright, continue.

Clone the `ng2-translate` repository somewhere on your file system. **NOT** inside your Angular project. Run `npm run build` and `npm link` inside your local `ng2-translate` repository.
Yes, this will create a global symlink, but this has nothing to do with Webpack or whatsoever. That's the beauty of `npm link`, it doesn't require changes in your configuration as to the application, it looks like it's installed from `npm`.

So far so good?

Go back to your angular application and first uninstall `ng2-translate` (`npm uninstall ng2-translate`). Now, instead of installing from `npm`, "install" from your local file system by running `npm link ng2-translate`. This will create the `ng2-translate` directory inside your `node_modules` folder that actually links to your local `ng2-translate` clone.
