### ISSUE TITLE
use interface instead of abstract class MissingTranslationHandler

### ISSUE THREAD

**Issue by ribizli** [ocombe/ng2-translate#48]
It is much easier (more flexible) to implement an interface than extend a class in Typescript. ```MissingTranslationHandler``` has no added value being a an abstract class.

(I'd also check ```TranslateLoader``` for the same, but it has a play with DI, where class might be desirable)

**Comment by ocombe** [comment]
You can implement an abstract class as well. How is it more flexible with an interface ?

**Comment by ribizli** [comment]
In a class you can have only one superclass but more implemented
interfaces. It's a minor thing, anyway.

**Comment by ocombe** [comment]
Hmm good to know, but can you write an interface that implements the abstract class and then implement this interface ?

**Comment by ribizli** [comment]
I'd replace the abstract class with interface.

**Comment by DanielSchuech** [comment]
I would agree in that case the the interface would be the better choice. I didn´t thought about this while implementing this feature.

Is your design maybe to complex? A class should only attend one responsibility to fulfill the Single Responsibility Principle. Maybe it would be better to devide your behabiour into different classes and MissingTranslationHandler inherit from just oneclass. That would be maybe better maintainable. But thats jsut an idee because I don`t know your use cases.

**Comment by ribizli** [comment]
I've just stumbled into this thing when I was reading the source. For me the rule of thumb is to use interface if I don't need to deliver default functionality. Since the abstract class don't have any implemented feature, it could be cleaner to be a simple interface.

The test implementation shows also, that this abstract class is anyway used as interface only:
```typescript
class Missing implements MissingTranslationHandler
```

**Comment by DanielSchuech** [comment]
@ribizli Yeah. As mentioned I agree with you.

**Comment by ocombe** [comment]
Yup good points, I'll change that for the next release

**Comment by ribizli** [comment]
I can prepare a PR for this and also create an NG2_TRANSLATE_PROVIDER for the default configuration. This is the proper angular2 way (like HTTP_PROVIDERS).

**Comment by ocombe** [comment]
ah yes good idea, thanks
