### ISSUE TITLE
Translation not working until change event

### ISSUE THREAD

**Issue by xkill-9** [ocombe/ng2-translate#98]
I came across with this issue while setting up ng2-translate using the latest angular2 "5 min quickstart", the page would load with every translatable string as an empty string until you fire any change event,  no errors were showing on the console.

At first i thought it was my server or something like that but after a lot of messing around the code i found out that the problem was the system_polyfills script, i just removed this line and everything worked as expected.

```
<script src="node_modules/systemjs/dist/system-polyfills.js"></script>
```

I don't know exactly what it is that interferes with the plugin, i'll just leave this here in case someone else has the same problem and/or knows why its happening.

**Comment by psurrey** [comment]
I am experiencing the same issue with angular 2.0.0-rc.1 and ng2-translate 2.1.0 in Internet Explorer 9 and 10 (using also router-deprecated 2.0.0-rc.1). If I hit a route with a component that has translations in the template the strings are all blank. If I tab through my input fields the validation kicks in and triggers a change event (to show validation errors). Then the translations are displayed correctly. 

I'm not sure why this happens. When I debug I'm able to see that in **TranslatePipe.updateValue** the lines `this.value = res ? res : key; this._ref.markForCheck();` are executed. `this.value` is the translated value already. So maybe the change detection is missing because of a timing issue in IE9, IE10?

I was able to fix this with by injecting NgZone into my AppComponent (top most component) and calling
`setTimeout(() => zone.run(() => {}), 0);`

**Comment by Booyanach** [comment]
Have the same issue as above, however instead of using an NgZone run went for ChangeDetectorRef.

ie:
```
    constructor(private cdr: ChangeDetectorRef) {...}

    ngAfterViewInit() {
        setTimeout(() => this.cdr.detectChanges(), 0);
    }
```

**Comment by zpul** [comment]
I experienced the same problem. I used the first a TranslatePipe after receiving a response from a web service. This resulted in requesting the translation file afterwards, but in this way I do end up with an empty string. (The inner updateValue observable actually returned the translated value, but the already built DOM object did not get the update).

I resolved by issuing a fake translate in the main page, so that when the response from the web service cames the translation service has already been inited.

I think that this is definitely a bug related with how change detection works... is there any information that I can provide to fix it in a better way? Thanks.

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it, I think this is resolved in one of the last versions.
